version: '2.1'

services:
  docker-js-livereload:
    image: docker-js-livereload
    build: .
    environment: 
      FRONT_PORT: 8080
      BACK_PORT: 3000
    volumes:
      - ./:/src/
      - src/node_modules
      - src/bin
    ports:
      - 3000:3000
      - 8080:8080